# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages

r_github_packages:
  - jtrecenti/rWordCloud
  
before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh
