---
title: "Convocação para assembleia"
date: "2017-07-31"
---

ASSOCIAÇÃO BRASILEIRA DE JURIMETRIA - ABJ

CNPJ/MF nº 13.612.840/0001-57

EDITAL DE CONVOCAÇÃO

ASSEMBLEIA GERAL ORDINÁRIA e EXTRAORDINÁRIA

Ficam convocados os associados a se reunirem em Assembleia Geral Ordinária e Extraordinária da Associação Brasileira de Jurimetria - ABJ ("ABJ"), que se realizará no dia 15 de agosto de 2017, às 09:00 hrs., em primeira convocação com presença de, no mínimo, mais da metade de associados quites, ou às 09:30hs, em segunda convocação, com presença de qualquer número de associados quites, na sede social da ABJ, na Rua Leopoldo Couto de Magalhães Jr., 146, 12o andar, São Paulo - SP, Brasil, CEP 04542-000, para examinar, discutir e votar a seguinte ordem do dia:

1.  Aprovação as contas referente ao exercício de 2016.
2.  Eleição da Diretoria e do Conselho Científico da ABJ para o próximo exercício.
3.  Alteração da sede da ABJ.
4.  Criação da categoria de associados Pessoa Jurídica.
5.  Alteração do Estatuto Social, com o objetivo de facilitar a participação em projetos de pesquisa junto ao Governo e entidades privadas.
6.  Outros eventuais assuntos de interesse dos associados.

O Estatuto Social com a consolidação das alterações propostas está disponível para consulta dos associados em versão virtual no site https://github.com/abjur/estatutoABJ e em versão física na sede da associação.

O presente edital será encaminhado aos associados por e-mail, bem como será disponibilizado no site da ABJ (www.abj.org.br), nos termos do Estatuto Social.

São Paulo, 31 de julho de 2017.

Marcelo Guedes Nunes
Presidente