---
title: "EDITAL DE CONVOCAÇÃO N.º 01/2017"
author: ASSOCIAÇÃO BRASILEIRA DE JURIMETRIA
date: "2017-12-04"
---

A Associação Brasileira de Jurimetria - ABJ, inscrita no CNPJ 13.612.840/0001-57, com sede e foro jurídico na cidade de São Paulo, sob o endereço Rua Gomes de Carvalho, 1356 – Vila Olímpia, faz saber que será realizado PROCESSO SELETIVO de pesquisadores para construção da base de dados da 2ª fase do projeto intitulado “Observatório de insolvência”. 

# 1. DO OBJETO

A presente convocação tem por objetivo selecionar interessados para contratação temporária e sem vínculo empregatício de profissionais para a prestação de serviços de pesquisador para a etapa de levantamento de informações sobre processos de recuperação judicial do estado de São Paulo.

# 2. DAS FUNÇÕES

2.1 A elaboração da base de dados consistirá em:

a. Participação em curso de formação a ser realizado no primeiro semestre de 2018.

b. Preenchimento de formulários com informações sobre os processos de recuperação judicial do estado de São Paulo.

c. Participação em reuniões de pesquisa presenciais ou online.

# 3. DOS CANDIDATOS ELEGÍVEIS

3.1 Os candidatos elegíveis atendem preferencialmente os seguintes critérios:

a. Estar cursando ou ter cursado o bacharelado em Direito.

b. Ser domiciliado em São Paulo - Capital.

c. Possuir experiência com pesquisa empírica.

d. Conhecer a legislação relativa à Recuperação Judicial.

e. Disponibilidade para execução da pesquisa no primeiro semestre de 2018.

# 4. DAS VAGAS

4.1 Serão ofertadas 5 (cinco) vagas.

4.2 Os candidatos classificados além do número de vagas ofertadas neste edital formarão um cadastro de reserva, para contratação conforme necessidade da ABJ.

# 5. DAS INSCRIÇÕES

5.1 As inscrições serão realizadas exclusivamente de forma eletrônica mediante o envio de um e-mail para o endereço eletrônico adm@abj.org.br até o dia 10/12/2017 com assunto “Edital Observatório da Insolvência” que deve conter:

a. Currículo Lattes ou vitae do candidato.

b. Descrição, se existente, da sua experiência de trabalho ou pesquisa relacionada a Direito Comercial.

c. Descrição de até duas páginas sobre as etapas de um processo de recuperação judicial.

5.2 A inscrição do candidato expressará sua integral adesão a todas as regras que disciplinam a presente seleção.

# 6. DA SELEÇÃO

6.1. A presente seleção poderá ser realizada em duas etapas, de caráter classificatório, sendo a segunda delas facultativa.

1. **Primeira Etapa**: análise curricular e dos demais materiais enviados por e-mail.

2. **Segunda Etapa**: entrevista presencial ou online.

6.2 O resultado final da seleção será publicado no sítio eletrônico http://abj.org.br.

# 7. DA CONTRATAÇÃO

7.1 Os candidatos classificados serão contratados para prestação de serviços no período compreendido entre 01 de fevereiro de 2018 à 30 de junho de 2018, sendo este período prorrogável mediante necessidade técnica.

7.2 As contratações poderão ser rescindidas, a qualquer tempo, quando:

a. verificar-se inexatidão ou irregularidade nas informações prestadas durante o processo seletivo;

b. verificada a ausência de idoneidade moral, assiduidade, disciplina, eficiência ou aptidão para o exercício da função que rege este edital. 

7.3. A remuneração fixada por pesquisador será definida após o período seleção dos candidatos.

# 8. DAS DISPOSIÇÕES FINAIS

8.1. A inscrição do candidato implicará na aceitação das normas do presente processo de seleção contidas neste edital e em outros instrumentos normativos e comunicados que vierem a surgir.

8.2. Nenhum candidato poderá alegar o desconhecimento das normas constantes do presente edital ou de qualquer outra norma e comunicado posterior regularmente divulgados, vinculados ao certame, ou utilizar-se de artifícios de forma a prejudicar este processo seletivo.

8.3. As listas de classificação serão divulgadas no sítio eletrônico http://abj.org.br

8.4. O prazo de validade desta seleção está de acordo com o item 5.1.

8.5. O candidato será responsável por todas as informações e declarações prestadas.

8.6. Os casos omissos neste edital serão analisados e deliberados pela coordenação executiva do projeto. 

