---
title: "Jurimetria societária e o cálculo das perdas com a queda no preço de ações negociadas em bolsa"
author: "Marcelo Guedes Nunes"
date: 2017-05-26T09:23:47-02:00
tags: ['metodologia', 'contrafactual', 'jurimetria']
banner: "img/banners/banner-15.png"
draft: false
---

Diante da profusão de escândalos envolvendo companhias brasileiras de capital aberto e da consequente queda nos valores de negociação de suas ações observada na bolsa de valores, começam a se discutir no Brasil os meios para caracterização e liquidação do prejuízo sofrido pelos acionistas decorrentes de ilícitos praticados no mercado. São as ações de responsabilização por perda de investimento societário, que começam a aparecer nos tribunais judiciais e arbitrais brasileiros, conhecidas nos EUA como "securities fraud lawsuits" ou " Não drop lawsuits".

A questão que pretendo discutir de maneira introdutória aqui é: caracterizados os requisitos legais para a condenação (matéria que tem complexidade suficiente para outro artigo e que por ora deixo de lado), é possível calcular o prejuízo? E em caso positivo, quais são as técnicas aplicáveis na apuração dos danos sofridos pelos acionistas nestes casos?

Minha resposta para a primeira questão é sim, é perfeitamente possível calcular o prejuízo sofrido em bases razoáveis, isolando a parcela do prejuízo causada pelo ato ilícito sobre o preço da ação. O que nos leva à discussão da segunda questão: como esse cálculo deve ser realizado?

Os danos sofridos são uma função da diferença entre o valor factual e o valor contrafactual da ação, multiplicado pela quantidade de ações negociadas. O valor factual equivale ao valor bursátil da ação (caso o acionista tenha carregado a posição) ou ao seu preço de venda (caso o acionista tenha vendido a posição), após o efeito do ato ilícito. Já o valor contrafactual é aquele equivalente ao preço pelo qual a ação estaria sendo negociada, caso o ato ilícito não tivesse ocorrido.

O valor factual da ação foi concretizado no mercado e, portanto, pode ser verificado através dos registros de negociação. Ainda assim, seu cálculo, em especial nos casos em que o acionista carregou a posição, levanta algumas questões interessantes como, por exemplo, qual data deve ser considerada como referência para sua fixação, ou qual intervalo de tempo deve ser utilizado para cálculo dos valores de negociação do período posterior ao ato ilícito. 

A ponderação dos preços ao longo de um período razoável de tempo tende a ser uma solução adequada para a maioria dos casos, tendo em vista a sensibilidade do mercado a notícias de fraude e a alta variabilidade dos preços decorrentes de boatos que sucedem à revelação do ato ilícito. Por exemplo, o US Code, título 15, capítulo 2 B, par. 78 U4, estabelece uma limitação para o cálculo do prejuízo com base no preço médio de negociação da ação nos 90 dias posteriores à data em que a informação do ilícito tenha sido disseminada no mercado.

Outro ponto diz respeito à metodologia de cálculo do valor factual. O valor médio é a resposta intuitiva imediata. No entanto, o julgador e o perito devem observar o comportamento dos preços, a fim de optar pela melhor maneira de ponderar esses valores e considerar não apenas a média, mas também a mediana, a variância, o desvio padrão ou uma combinação de medidas de posição e de dispersão, que seja capaz de resumir os preços praticados naquele período.

Há também acionistas que adquiriram e venderam posições antes do ato ilícito e/ou que, diante da queda abrupta, optaram por comprar mais ações no mercado para melhorar seu preço médio de aquisição. Diante dessas circunstâncias, é importante delimitar não apenas o período de venda posterior ao ato, mas também o período de aquisição anterior ao ato abrangido pelo dever de indenizar. Esse período anterior permite ponderar eventuais ganhos realizados antes da ocorrência do ato ilícito (o acionista pode ter se beneficiado da fraude no passado, vendendo no mercado ações sobrevalorizadas), bem como excluir do multiplicador ações adquiridas após o ilícito.

Já o cálculo do valor contrafactual da ação levanta outras questões, tendo em vista a sua abstração, ou seja, a circunstância desse preço não ter se materializado em uma negociação de mercado. Por quanto

Fernando Filho, [26.05.17 16:17]
essa ação estaria sendo negociada caso o ato ilícito não tivesse ocorrido? Essa pergunta leva a outra indagação, relacionada ao nexo de causalidade e usualmente explorada pela defesa: existiriam outras causas concorrentes capazes de explicar a queda no valor da ação, além da ocorrência do ato ilícito?

O cálculo do valor contrafacutual pode ser realizado através de comparações em três níveis: 1. A companhia com ela própria (auto comparação). 2. A companhia com outras companhias parecidas (comparação com semelhantes). 3. A companhia com o indicadores econômicos (comparação com o mercado). 

A auto comparação procura identificar tendências de evolução no preço da ação antes do ato ilícito e projetar qual teria sido aproximadamente o valor contrafactual da ação, caso ele não tivesse ocorrido. A limitação desse método reside na suposição de que todos os demais fatores de mercado observados antes do ato ilícito, bem como as características internas da companhia, permaneceriam constantes, o que pode não ser verdade.

A comparação com semelhantes procura associar o preço da ação antes do ato ilícito com o preço de mercado de outras empresas no mesmo período. Se há na bolsa mais companhias que atuam no mesmo segmento, que não sofreram o efeito do ato ilícito e cujo preço de negociação da ação está associado ao preço da ação da companhia sujeita ao processo de indenização, esse preço pode ser utilizado como referência para o cálculo. A limitação aqui é que podem não existir outras companhias no mesmo segmento com ações negociadas na bolsa ou, ainda que existam, esses preços podem ter sido indiretamente contaminados pelo ato ilícito.

Por fim, a comparação com o mercado consiste em associar o preço da ação antes do ato ilícito com indicadores de mercado, micro e macroeconômicos, em uma técnica que permite isolar o efeito do ilícito de outros efeitos genéricos do mercado, tais como evolução do produto interno bruto, taxa de desemprego e índice de inflação, para citar os mais notórios.

Esses três caminhos não se excluem mutuamente e podem ser combinados em uma solução ótima, que permita obter um valor contrafactual que considere as características próprias da companhia em discussão e, ao mesmo tempo, controle outras possíveis causas de variação do preço, como o comportamento do segmento de mercado em que ela atua e o desempenho geral da economia do país. 

Quero enfatizar, por fim, que o cálculo é perfeitamente viável de ser realizado. Também ressalto que o mais importante nessa avaliação é admitir a sua contrafactualidade, reconhecer a existência de outras causas para a formação do preço (covariantes explicativas) e, ao final, ao invés de apresentar um número de ouro sem credibilidade, oferecer ao julgador um conjunto de cenários verossímeis, capaz de apresentar um intervalo razoável de valores a ser considerado pelo juiz no momento da fixação da indenização.